import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Desired_BillRate } from './desired-billrate';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class ApiService {

  constructor(public http:HttpClient) { }

  getAllData()
  {
    return this.http.get('http://localhost:3000/Desired-billrate') as Observable<Desired_BillRate[]>

  }
  Employee_data : string[]=[
  'Gaurav Gupta',
  'Sandhya Baskar',
  'Madasamy Guruvaiah',
  'Vijayalakshmi Raju',
  'Ramya M',
  'Aravind Kumar Kondaji',
  'Jamuna M',
  'Supreeth Balasubramanya',
  'Siva Subramonian',
  'Saran Viswanath',
  'Dharani T',
  'Venkatesan Ramanujam',
  'Jayasree Rajan',
  'Prabu Arumugam',
  'Monicavinodhini Mohan',
  'Hemanth Babu',
  'Haripriya Prasanna',
  'Gowtham Balasubramaniyam',
  'Bhuvaneswari Duraisamy',
  'Ajay Viswam Kumaraswamy',
  'Bharath Balamurugan',
  'Venkatesan Muthukrishnan',
  'Naveenkumar Baskar',
  'Sathishkumar Ravi',
  'Pranes Narayanamoorthi',
  'Sumathi Krishnasamy',
  'Vinu Vignesh',
  'Mohamed Noordheen',
  'Tamilarasan Vimalendran',
  'Gopi Saravana muthu',
  'Uthith Narayanan Thirumaran',
  'Nandhinidevi Sanjeevi',
  'Aparajith Varun Veeraraghavan',
  'Josephin Monika Xavier',
  'Pavithra Ramamoorthi',
  'Porchelvi Selvaraj',
  'Kavin Kumar Senthilkumar',
  'Ameena Begam Syed Akbar',
  'Hari Krishnan Muthu Ganesan',
  'Vijaya Raja Venugopal',
  'Vaishali Jeyaprakkash',
  'Abhirami Thiagarajan',
  'Mani Kumar M V Prasanna',
  'Punitha Pannerselvam',
  'Shamilipriya Kothandaraman',
  'Vignesan Saravanan',
  'Kamal Rajeshwaran V',
  'RenithKumar Senthil',
  'Sivasathivel Moorthy',
  'Rakesh Krishna',
  'Jeffrey Daniel',
  'Kishorkumar Mohan Raj',
  'Vasanth kannan',
  'Abhishek Prashant Hatkar',
  'Rahinipriya Ramakrishnan',
  'Jeffrin Salomi Sudhakar',
  'Divyapriya Bathirappan',
  'Soundharya Vivekanandan',
  'Gokul Krish Govindaraj',
  'Ishwariya Sukumar',
  'Mukesh Ravi Chandran',
  'Sivakumar Arjunan',
  'Vishal Chandrasekaran',
  'Vamsi Krishna Gumma Venkata',
  'Krapali Sikarwar',
  'Naveen Jayandiran',
  'Pooja Subramanian',
  'Suresh Mohan',
  'Manubolu Sai Kumar',
  'Sree Ranjitha T G',
  'Amaresh Jupalli',
  'Supriya S',
  'Mankaran Singh Saggu',
  'Sri Ranga Guru Linga Sastry Kadaru',
  'Prabhakaran Vasudevan',
  'Mohamedha Rifana',
  'Robinson Albert',
  'Sriram Vaideeswaran',
  'Shanmukh Rao Teleganeni',
  'Thirumurugan kathir Periyathambi',
  'Lakshnaa Shri',
  'Jegan Kathirvel',
  'Priya Kandhaswamy',
  'Kowsalya Sengamalai',
  'Karishma Marimuthu',
  'Rajesh Sundaramurthy',
  'Krishnarajan Devarajan',
  'Madhusoothanan Balakrishnan',
  'Srinath Ravi',
  'Sathishkumar Loganathan',
  'Madhusudhanan Ponnurangam',
  'Vaideeswaran Ramakrishnan',
  'Jayaram Sadasivam',
  'Joe Devalla',
  'Raj Sundaram',
  'HR Admin',
  'Sampath Kumar Vaikuntan',
  'Allu Radhika Krishna',
  'Gautham A',
  'Subash Chander V',
  'Aravind J.M',
  'Vithyasree S',
  'Reetu Wilson',
  'Sathishkumar Govindharaj',
  'Anandharaj Venkatesan',
  'Sankar R.S',
  'Divya Vijaykumar Nair',
  'Shaly Angel Baby Jebaraj',
  'Radhakrishna K',
  'Jeyabharathi R',
  'Santhoshkumar Sundaramoorthy',
  'Balaji Muthuswamy',
  'Pradhiba Ayyadurai',
  'Santhini Thangaraj',
  'Saravanakumar Palanisamy',
  'Bhagyalakshmi Murugesan',
  'Sridhar Santhanakrishnan',
  'Divya Surya',
  'Mercy Diana',
  'Swati Dasgupta',
  'Dhivya Thathineni',
  'Anthony Angel',
  'Vimalraj Selvaraj',
  'Manju Bashini',
  'Bhagiyalakshmi Gunasekaran',
  'Prakashraj Shanmugam',
  'Sriram Vaidiyanathan',
  'Ramakrishnan R',
  'Pushpa Velayutham',
  'Swaminathan Sundararajan',
  'Siva Anandan',
  'Sonali Kannan',
  'Kannappan Kailasam Sundaram',
  'Saravanan Sandhirasekaran',
  'Arun Mohan',
  'Pasupathy Chandran',
  'Manikya Chandrasekara',
  'Manikandan Selvaraj',
  'Priscilla Nancy',
  'Anantharaj Raja',
  'Vinitha Thirumoorthy',
  'Nithya Shalini',
  'Vishal Sivanarayanan',
  'Evandle Titus',
  'Chandrasekar Ramadoss',
  'Karthik Kumar M',
  'Ajai Joseph',
  'Karthikeyan Ramadoss',
  'Karthikeyan Devalla',
  'Vikram Sundaresan',
  'Naveenkumar Srinivasan',
  'Abdul Qayyum Babulkhair',
  'Madhumathy Rajaram'
  ];
}


